apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels: {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      name: http
      # Port accessible inside cluster
      port: {{ .Values.service.port }}
      # Port to forward to inside the pod
      targetPort: http
      # Port accessible outside cluster
      nodePort: {{ .Values.service.nodePort }}
  selector: {{- include "frontend.selectorLabels" . | nindent 4 }}
