stages:
  - sonarqube_check
  - build_front
  - build-docker
  - k8s

default:
  tags:
    - main

variables:
  APP: frontend-react


sonarQube:
  stage: sonarqube_check
  image: sonarsource/sonar-scanner-cli:4.6
  variables:
    SONAR_PROJECT_BASE_DIR: "$CI_PROJECT_DIR"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: 0 # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
      - .sonar/cache
      - .scannerwork
  script:
    - /usr/bin/entrypoint.sh sonar-scanner -Dproject.settings=ci/sonar-project.properties
      -Dsonar.projectKey=a-banking-new-front-react
      -Dsonar.projectName=a-banking-new-front-react
      -Dsonar.projectVersion=1.0
      -Dsonar.links.ci=$CI_PIPELINE_URL
  allow_failure: true
  only:
    - merge_requests
    - develop

build_front_path:
  stage: build_front
  image: node:16.14.2-alpine3.14
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
  script:
    - npm install
    - unset CI
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build
    expire_in: 2h
  only:
    - merge_requests
    - develop

build-docker-dev:
  stage: build-docker
  image:
    name: gcr.io/kaniko-project/executor:debug-v1.3.0
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$AND_DOCKER_REGISTRY_NAME\":{\"username\":\"$AND_DOCKER_REGISTRY_USER\",\"password\":\"$AND_DOCKER_REGISTRY_RW_PASS\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
      --cache=true --cache-repo=a-banking-new-$APP-dev \
      --dockerfile $CI_PROJECT_DIR/ci/Dockerfile \
      --destination $AND_DOCKER_REGISTRY_NAME/a-banking-new-$APP-dev:$CI_COMMIT_SHORT_SHA

  only:
    - develop

k8s:
  stage: k8s
  tags: [deploer]
  script:
    - helm upgrade --install frontend-react ci/frontend/ --namespace dev
        --set image.tag=$CI_COMMIT_SHORT_SHA -f ci/values.dev.yaml
        --debug
        --timeout 200s
  only:
    - develop
