replicaCount: 1

fullnameOverride: frontend-react

image:
  repository: a-banking-new-frontend-react-dev
  pullPolicy: IfNotPresent
  tag: "latest"
  secrets: and-registry

service:
  type: NodePort
  port: 8081
  nodePort: 30004

resources:
  limits:
    memory: 256Mi
  requests:
    memory: 64Mi
